INSERT INTO tb_pesquisa (
    jogo_online_favorito,
    esporte_favorito,
    viagem_dos_sonhos,
    meme_favorito,
    calcado_favorito,
    cantor_favorito,
    jogador_favorito,
    filme_favorito,
    materia_preferida,
    lugar_favorito,
    marca_preferida,
    horas_sono
) VALUES
('Minecraft', 'Futebol', 'Japão', 'Gato', 'Nike', 'Bruno Mars', 'Neymar', 'Vingadores', 'Matemática', 'Praia', 'Nike', 8),
('Free Fire', 'Vôlei', 'Estados Unidos', 'Risada', 'Adidas', 'Taylor Swift', 'Messi', 'Titanic', 'História', 'Shopping', 'Adidas', 7),
('Fortnite', 'Basquete', 'França', 'Drake', 'Puma', 'The Weeknd', 'Cristiano Ronaldo', 'Avatar', 'Geografia', 'Parque', 'Puma', 6),
('Roblox', 'Futebol', 'Itália', 'Cachorro', 'Nike', 'Ed Sheeran', 'Vini Jr.', 'Homem-Aranha', 'Português', 'Praia', 'Nike', 8),
('Valorant', 'Futebol', 'Japão', 'Gato', 'Adidas', 'Bruno Mars', 'Neymar', 'Vingadores', 'Matemática', 'Cinema', 'Adidas', 7),
('Minecraft', 'Vôlei', 'Canadá', 'Risada', 'Nike', 'Taylor Swift', 'Messi', 'Harry Potter', 'Ciências', 'Praia', 'Nike', 9),
('Free Fire', 'Futebol', 'Estados Unidos', 'Gato', 'Puma', 'The Weeknd', 'Cristiano Ronaldo', 'Vingadores', 'Educação Física', 'Estádio', 'Puma', 8),
('Fortnite', 'Basquete', 'Japão', 'Cachorro', 'Nike', 'Bruno Mars', 'Vini Jr.', 'Avatar', 'Matemática', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'França', 'Drake', 'Adidas', 'Ed Sheeran', 'Neymar', 'Titanic', 'História', 'Praia', 'Adidas', 7),
('Minecraft', 'Futebol', 'Itália', 'Gato', 'Nike', 'Taylor Swift', 'Messi', 'Harry Potter', 'Português', 'Cinema', 'Nike', 8),

('Free Fire', 'Vôlei', 'Japão', 'Risada', 'Adidas', 'Bruno Mars', 'Cristiano Ronaldo', 'Vingadores', 'Matemática', 'Praia', 'Adidas', 7),
('Fortnite', 'Futebol', 'Estados Unidos', 'Gato', 'Puma', 'The Weeknd', 'Neymar', 'Avatar', 'Geografia', 'Parque', 'Puma', 8),
('Minecraft', 'Basquete', 'Canadá', 'Cachorro', 'Nike', 'Ed Sheeran', 'Vini Jr.', 'Homem-Aranha', 'Ciências', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Japão', 'Drake', 'Adidas', 'Taylor Swift', 'Messi', 'Titanic', 'História', 'Praia', 'Adidas', 9),
('Valorant', 'Futebol', 'França', 'Gato', 'Nike', 'Bruno Mars', 'Neymar', 'Vingadores', 'Matemática', 'Cinema', 'Nike', 8),
('Minecraft', 'Vôlei', 'Itália', 'Risada', 'Puma', 'The Weeknd', 'Cristiano Ronaldo', 'Harry Potter', 'Português', 'Praia', 'Puma', 7),
('Free Fire', 'Futebol', 'Japão', 'Gato', 'Nike', 'Ed Sheeran', 'Vini Jr.', 'Avatar', 'Educação Física', 'Estádio', 'Nike', 8),
('Fortnite', 'Basquete', 'Estados Unidos', 'Cachorro', 'Adidas', 'Taylor Swift', 'Messi', 'Vingadores', 'Matemática', 'Shopping', 'Adidas', 6),
('Roblox', 'Futebol', 'Canadá', 'Drake', 'Nike', 'Bruno Mars', 'Neymar', 'Homem-Aranha', 'História', 'Praia', 'Nike', 7),
('Minecraft', 'Futebol', 'Japão', 'Gato', 'Adidas', 'The Weeknd', 'Cristiano Ronaldo', 'Titanic', 'Geografia', 'Cinema', 'Adidas', 8),

('Free Fire', 'Vôlei', 'França', 'Risada', 'Nike', 'Taylor Swift', 'Messi', 'Harry Potter', 'Português', 'Praia', 'Nike', 7),
('Fortnite', 'Futebol', 'Itália', 'Gato', 'Puma', 'Bruno Mars', 'Vini Jr.', 'Vingadores', 'Matemática', 'Estádio', 'Puma', 8),
('Minecraft', 'Basquete', 'Estados Unidos', 'Cachorro', 'Nike', 'Ed Sheeran', 'Neymar', 'Avatar', 'Ciências', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Japão', 'Drake', 'Adidas', 'The Weeknd', 'Cristiano Ronaldo', 'Homem-Aranha', 'História', 'Praia', 'Adidas', 9),
('Valorant', 'Futebol', 'Canadá', 'Gato', 'Nike', 'Taylor Swift', 'Messi', 'Vingadores', 'Matemática', 'Cinema', 'Nike', 8),
('Minecraft', 'Vôlei', 'França', 'Risada', 'Adidas', 'Bruno Mars', 'Neymar', 'Titanic', 'Geografia', 'Praia', 'Adidas', 7),
('Free Fire', 'Futebol', 'Itália', 'Gato', 'Puma', 'Ed Sheeran', 'Vini Jr.', 'Harry Potter', 'Português', 'Parque', 'Puma', 8),
('Fortnite', 'Basquete', 'Japão', 'Cachorro', 'Nike', 'Taylor Swift', 'Cristiano Ronaldo', 'Avatar', 'Matemática', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Estados Unidos', 'Drake', 'Adidas', 'The Weeknd', 'Messi', 'Vingadores', 'Educação Física', 'Praia', 'Adidas', 7),
('Minecraft', 'Futebol', 'Japão', 'Gato', 'Nike', 'Bruno Mars', 'Neymar', 'Homem-Aranha', 'Matemática', 'Cinema', 'Nike', 8),

('Free Fire', 'Vôlei', 'Canadá', 'Risada', 'Adidas', 'Taylor Swift', 'Cristiano Ronaldo', 'Titanic', 'História', 'Praia', 'Adidas', 9),
('Fortnite', 'Futebol', 'França', 'Gato', 'Puma', 'Bruno Mars', 'Vini Jr.', 'Vingadores', 'Geografia', 'Estádio', 'Puma', 7),
('Minecraft', 'Basquete', 'Itália', 'Cachorro', 'Nike', 'The Weeknd', 'Messi', 'Avatar', 'Ciências', 'Shopping', 'Nike', 8),
('Roblox', 'Futebol', 'Japão', 'Drake', 'Adidas', 'Ed Sheeran', 'Neymar', 'Harry Potter', 'Português', 'Praia', 'Adidas', 6),
('Valorant', 'Futebol', 'Estados Unidos', 'Gato', 'Nike', 'Taylor Swift', 'Cristiano Ronaldo', 'Vingadores', 'Matemática', 'Cinema', 'Nike', 8),
('Minecraft', 'Vôlei', 'França', 'Risada', 'Puma', 'Bruno Mars', 'Vini Jr.', 'Homem-Aranha', 'Educação Física', 'Praia', 'Puma', 7),
('Free Fire', 'Futebol', 'Itália', 'Gato', 'Nike', 'The Weeknd', 'Messi', 'Titanic', 'História', 'Estádio', 'Nike', 8),
('Fortnite', 'Basquete', 'Canadá', 'Cachorro', 'Adidas', 'Taylor Swift', 'Neymar', 'Avatar', 'Matemática', 'Shopping', 'Adidas', 6),
('Roblox', 'Futebol', 'Japão', 'Drake', 'Nike', 'Ed Sheeran', 'Cristiano Ronaldo', 'Vingadores', 'Geografia', 'Praia', 'Nike', 7),
('Minecraft', 'Futebol', 'Estados Unidos', 'Gato', 'Adidas', 'Bruno Mars', 'Vini Jr.', 'Harry Potter', 'Português', 'Cinema', 'Adidas', 8),

('Free Fire', 'Vôlei', 'Japão', 'Risada', 'Nike', 'Taylor Swift', 'Messi', 'Vingadores', 'Matemática', 'Praia', 'Nike', 7),
('Fortnite', 'Futebol', 'França', 'Gato', 'Puma', 'The Weeknd', 'Neymar', 'Avatar', 'Ciências', 'Parque', 'Puma', 8),
('Minecraft', 'Basquete', 'Itália', 'Cachorro', 'Nike', 'Bruno Mars', 'Cristiano Ronaldo', 'Homem-Aranha', 'História', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Canadá', 'Drake', 'Adidas', 'Ed Sheeran', 'Vini Jr.', 'Titanic', 'Geografia', 'Praia', 'Adidas', 9),
('Valorant', 'Futebol', 'Japão', 'Gato', 'Nike', 'Taylor Swift', 'Messi', 'Vingadores', 'Matemática', 'Cinema', 'Nike', 8),
('Minecraft', 'Vôlei', 'Estados Unidos', 'Risada', 'Adidas', 'Bruno Mars', 'Neymar', 'Harry Potter', 'Português', 'Praia', 'Adidas', 7),
('Free Fire', 'Futebol', 'França', 'Gato', 'Puma', 'The Weeknd', 'Cristiano Ronaldo', 'Avatar', 'Educação Física', 'Estádio', 'Puma', 8),
('Fortnite', 'Basquete', 'Itália', 'Cachorro', 'Nike', 'Taylor Swift', 'Vini Jr.', 'Vingadores', 'Matemática', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Japão', 'Drake', 'Adidas', 'Ed Sheeran', 'Messi', 'Homem-Aranha', 'História', 'Praia', 'Adidas', 7),
('Minecraft', 'Futebol', 'Canadá', 'Gato', 'Nike', 'Bruno Mars', 'Neymar', 'Titanic', 'Geografia', 'Cinema', 'Nike', 8),

('Free Fire', 'Vôlei', 'Itália', 'Risada', 'Adidas', 'Taylor Swift', 'Cristiano Ronaldo', 'Vingadores', 'Matemática', 'Praia', 'Adidas', 7),
('Fortnite', 'Futebol', 'Japão', 'Gato', 'Puma', 'Bruno Mars', 'Vini Jr.', 'Avatar', 'Ciências', 'Estádio', 'Puma', 8),
('Minecraft', 'Basquete', 'Estados Unidos', 'Cachorro', 'Nike', 'The Weeknd', 'Messi', 'Harry Potter', 'Português', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'França', 'Drake', 'Adidas', 'Ed Sheeran', 'Neymar', 'Vingadores', 'História', 'Praia', 'Adidas', 9),
('Valorant', 'Futebol', 'Canadá', 'Gato', 'Nike', 'Taylor Swift', 'Cristiano Ronaldo', 'Titanic', 'Matemática', 'Cinema', 'Nike', 8),
('Minecraft', 'Vôlei', 'Japão', 'Risada', 'Puma', 'Bruno Mars', 'Vini Jr.', 'Avatar', 'Geografia', 'Praia', 'Puma', 7),
('Free Fire', 'Futebol', 'Itália', 'Gato', 'Nike', 'The Weeknd', 'Messi', 'Vingadores', 'Educação Física', 'Estádio', 'Nike', 8),
('Fortnite', 'Basquete', 'Estados Unidos', 'Cachorro', 'Adidas', 'Taylor Swift', 'Neymar', 'Homem-Aranha', 'Matemática', 'Shopping', 'Adidas', 6),
('Roblox', 'Futebol', 'Japão', 'Drake', 'Nike', 'Ed Sheeran', 'Cristiano Ronaldo', 'Harry Potter', 'História', 'Praia', 'Nike', 7),
('Minecraft', 'Futebol', 'França', 'Gato', 'Adidas', 'Bruno Mars', 'Vini Jr.', 'Vingadores', 'Português', 'Cinema', 'Adidas', 8),

('Free Fire', 'Vôlei', 'Canadá', 'Risada', 'Nike', 'Taylor Swift', 'Messi', 'Avatar', 'Matemática', 'Praia', 'Nike', 7),
('Fortnite', 'Futebol', 'Japão', 'Gato', 'Puma', 'The Weeknd', 'Neymar', 'Vingadores', 'Geografia', 'Parque', 'Puma', 8),
('Minecraft', 'Basquete', 'Itália', 'Cachorro', 'Nike', 'Bruno Mars', 'Cristiano Ronaldo', 'Titanic', 'Ciências', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Estados Unidos', 'Drake', 'Adidas', 'Ed Sheeran', 'Vini Jr.', 'Harry Potter', 'História', 'Praia', 'Adidas', 9),
('Valorant', 'Futebol', 'Japão', 'Gato', 'Nike', 'Taylor Swift', 'Messi', 'Vingadores', 'Matemática', 'Cinema', 'Nike', 8),
('Minecraft', 'Vôlei', 'França', 'Risada', 'Adidas', 'Bruno Mars', 'Neymar', 'Homem-Aranha', 'Português', 'Praia', 'Adidas', 7),
('Free Fire', 'Futebol', 'Canadá', 'Gato', 'Puma', 'The Weeknd', 'Cristiano Ronaldo', 'Avatar', 'Educação Física', 'Estádio', 'Puma', 8),
('Fortnite', 'Basquete', 'Itália', 'Cachorro', 'Nike', 'Taylor Swift', 'Vini Jr.', 'Vingadores', 'Matemática', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Japão', 'Drake', 'Adidas', 'Ed Sheeran', 'Messi', 'Titanic', 'História', 'Praia', 'Adidas', 7),
('Minecraft', 'Futebol', 'Estados Unidos', 'Gato', 'Nike', 'Bruno Mars', 'Neymar', 'Harry Potter', 'Geografia', 'Cinema', 'Nike', 8),

('Free Fire', 'Vôlei', 'Japão', 'Risada', 'Adidas', 'Taylor Swift', 'Cristiano Ronaldo', 'Vingadores', 'Matemática', 'Praia', 'Adidas', 7),
('Fortnite', 'Futebol', 'França', 'Gato', 'Puma', 'The Weeknd', 'Vini Jr.', 'Avatar', 'Ciências', 'Estádio', 'Puma', 8),
('Minecraft', 'Basquete', 'Canadá', 'Cachorro', 'Nike', 'Bruno Mars', 'Messi', 'Homem-Aranha', 'História', 'Shopping', 'Nike', 6),
('Roblox', 'Futebol', 'Itália', 'Drake', 'Adidas', 'Ed Sheeran', 'Neymar', 'Titanic', 'Português', 'Praia', 'Adidas', 9),
('Valorant', 'Futebol', 'Japão', 'Gato', 'Nike', 'Taylor Swift', 'Cristiano Ronaldo', 'Vingadores', 'Matemática', 'Cinema', 'Nike', 8),
('Minecraft', 'Vôlei', 'Estados Unidos', 'Risada', 'Puma', 'Bruno Mars', 'Vini Jr.', 'Harry Potter', 'Geografia', 'Praia', 'Puma', 7),
('Free Fire', 'Futebol', 'França', 'Gato', 'Nike', 'The Weeknd', 'Messi', 'Avatar', 'Educação Física', 'Estádio', 'Nike', 8),
('Fortnite', 'Basquete', 'Itália', 'Cachorro', 'Adidas', 'Taylor Swift', 'Neymar', 'Vingadores', 'Matemática', 'Shopping', 'Adidas', 6),
('Roblox', 'Futebol', 'Canadá', 'Drake', 'Nike', 'Ed Sheeran', 'Cristiano Ronaldo', 'Homem-Aranha', 'História', 'Praia', 'Nike', 7),
('Minecraft', 'Futebol', 'Japão', 'Gato', 'Adidas', 'Bruno Mars', 'Vini Jr.', 'Titanic', 'Português', 'Cinema', 'Adidas', 8);